# Generated by Django 4.1.1 on 2022-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_title_articlemodel_název článku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='Název článku',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='tag',
            field=models.ManyToManyField(help_text='vyber 1 či více kategorií, v které se má čánek zobrazovat', related_name='articles', to='blog.articletagmodel', verbose_name='Kategorie'),
        ),
    ]
