# Generated by Django 4.1.1 on 2022-09-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_articlemodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletagmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název kategorie'),
        ),
    ]
