# Generated by Django 4.1.1 on 2022-09-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_articletagmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ['-edited'], 'verbose_name': 'Článek', 'verbose_name_plural': 'Články'},
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='created',
            new_name='edited',
        ),
    ]
