# Generated by Django 4.1.1 on 2022-09-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_articlemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ['-created'], 'verbose_name': 'Článek', 'verbose_name_plural': 'Články'},
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='edited',
            new_name='created',
        ),
    ]
