# Generated by Django 4.1.1 on 2022-09-26 08:29

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_articlemodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='thumbnail',
            field=models.ImageField(default='global/img/build.png', upload_to=blog.models.ArticleModel.thumbnail_directory_path, verbose_name='Mini-obrázek'),
        ),
    ]
